import { Player } from './types';

export const INITIAL_MOCK_PLAYERS: Player[] = [
  // Forward (FWD)
  {
    id: 'haaland-09',
    name: 'Erling Haaland',
    club: 'Man City',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 27,
    assists: 5,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 4,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 1,
    points: 217,
    recentPoints: [12, 6, 2, 8, 15],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'salah-11',
    name: 'Mohamed Salah',
    club: 'Liverpool',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 18,
    assists: 10,
    cleanSheets: 12,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 2,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 211,
    recentPoints: [7, 10, 8, 3, 14],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'saka-07',
    name: 'Bukayo Saka',
    club: 'Arsenal',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 14,
    assists: 12,
    cleanSheets: 14,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 1,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 198,
    recentPoints: [8, 5, 12, 6, 4],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'palmer-20',
    name: 'Cole Palmer',
    club: 'Chelsea',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 22,
    assists: 11,
    cleanSheets: 6,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 7,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 244,
    recentPoints: [2, 18, 9, 7, 5],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'son-07',
    name: 'Heung-min Son',
    club: 'Spurs',
    position: 'MID',
    injuryStatus: 'Doubtful',
    injuryDetails: 'Hamstring tightening',
    news: 'Expected to be tested before gameweek start',
    goals: 12,
    assists: 9,
    cleanSheets: 7,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 0,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 145,
    recentPoints: [5, 4, 1, 0, 8],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'watkins-11',
    name: 'Ollie Watkins',
    club: 'Aston Villa',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 19,
    assists: 13,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 188,
    recentPoints: [6, 11, 2, 5, 9],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'isak-14',
    name: 'Alexander Isak',
    club: 'Newcastle',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 21,
    assists: 2,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 1,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 1,
    points: 172,
    recentPoints: [13, 2, 7, 10, 2],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'foden-47',
    name: 'Phil Foden',
    club: 'Man City',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 11,
    assists: 8,
    cleanSheets: 7,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 2,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 138,
    recentPoints: [3, 9, 6, 2, 10],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'fernandes-08',
    name: 'Bruno Fernandes',
    club: 'Man Utd',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 10,
    assists: 9,
    cleanSheets: 8,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 8,
    redCards: 1,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 154,
    recentPoints: [5, 8, 3, 11, 4],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'maddison-10',
    name: 'James Maddison',
    club: 'Spurs',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 7,
    assists: 10,
    cleanSheets: 5,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 4,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 119,
    recentPoints: [2, 7, 5, 4, 3],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'bowen-20',
    name: 'Jarrod Bowen',
    club: 'West Ham',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 16,
    assists: 6,
    cleanSheets: 5,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 165,
    recentPoints: [9, 2, 6, 8, 5],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'mbeumo-19',
    name: 'Bryan Mbeumo',
    club: 'Brentford',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 9,
    assists: 6,
    cleanSheets: 4,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 2,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 112,
    recentPoints: [8, 5, 2, 10, 3],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'jpedro-09',
    name: 'João Pedro',
    club: 'Brighton',
    position: 'FWD',
    injuryStatus: 'Injured',
    injuryDetails: 'Ankle knock',
    news: 'Out definitely for the upcoming round',
    goals: 9,
    assists: 3,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 95,
    recentPoints: [0, 0, 0, 0, 0],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'solanke-09',
    name: 'Dominic Solanke',
    club: 'Spurs',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 15,
    assists: 3,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 1,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 139,
    recentPoints: [2, 12, 6, 4, 8],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'havertz-29',
    name: 'Kai Havertz',
    club: 'Arsenal',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 13,
    assists: 7,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 5,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 142,
    recentPoints: [7, 3, 10, 5, 2],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'jackson-15',
    name: 'Nicolas Jackson',
    club: 'Chelsea',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 14,
    assists: 5,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 9,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 131,
    recentPoints: [4, 8, 2, 11, 5],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'cunha-10',
    name: 'Matheus Cunha',
    club: 'Wolves',
    position: 'FWD',
    injuryStatus: 'Available',
    goals: 12,
    assists: 7,
    cleanSheets: 0,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 6,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 128,
    recentPoints: [5, 2, 14, 6, 3],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'gordon-10',
    name: 'Anthony Gordon',
    club: 'Newcastle',
    position: 'MID',
    injuryStatus: 'Available',
    goals: 11,
    assists: 10,
    cleanSheets: 9,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 6,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 158,
    recentPoints: [3, 8, 4, 11, 7],
    ownershipStatus: { isOwned: false }
  },
  // Defenders (DEF)
  {
    id: 'alexander-arnold-66',
    name: 'Trent Alexander-Arnold',
    club: 'Liverpool',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 3,
    assists: 9,
    cleanSheets: 13,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 4,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 142,
    recentPoints: [6, 12, 2, 7, 15],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'gabriel-06',
    name: 'Gabriel Magalhães',
    club: 'Arsenal',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 4,
    assists: 1,
    cleanSheets: 15,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 135,
    recentPoints: [6, 6, 15, 2, 6],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'saliba-02',
    name: 'William Saliba',
    club: 'Arsenal',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 2,
    assists: 1,
    cleanSheets: 15,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 2,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 129,
    recentPoints: [6, 6, 6, 2, 6],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'porro-23',
    name: 'Pedro Porro',
    club: 'Spurs',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 3,
    assists: 7,
    cleanSheets: 7,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 120,
    recentPoints: [5, 2, 4, 11, 2],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'gvardiol-24',
    name: 'Joško Gvardiol',
    club: 'Man City',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 4,
    assists: 2,
    cleanSheets: 8,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 115,
    recentPoints: [2, 12, 1, 6, 5],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'vandijk-04',
    name: 'Virgil van Dijk',
    club: 'Liverpool',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 2,
    assists: 2,
    cleanSheets: 13,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 2,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 125,
    recentPoints: [6, 6, 8, 2, 11],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'dalot-20',
    name: 'Diogo Dalot',
    club: 'Man Utd',
    position: 'DEF',
    injuryStatus: 'Suspended',
    injuryDetails: 'Accumulated yellow cards',
    news: 'Suspended for one match',
    goals: 2,
    assists: 3,
    cleanSheets: 8,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 10,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 92,
    recentPoints: [0, 5, 2, 1, 0],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'trippier-02',
    name: 'Kieran Trippier',
    club: 'Newcastle',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 1,
    assists: 10,
    cleanSheets: 9,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 5,
    redCards: 0,
    ownGoals: 1,
    penaltiesMissed: 0,
    points: 105,
    recentPoints: [1, 2, 5, 12, 2],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'colwill-06',
    name: 'Levi Colwill',
    club: 'Chelsea',
    position: 'DEF',
    injuryStatus: 'Available',
    goals: 1,
    assists: 1,
    cleanSheets: 6,
    saves: 0,
    penaltiesSaved: 0,
    yellowCards: 4,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 75,
    recentPoints: [1, 5, 2, 6, 2],
    ownershipStatus: { isOwned: false }
  },
  // Goalkeepers (GKP)
  {
    id: 'raya-01',
    name: 'David Raya',
    club: 'Arsenal',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 0,
    cleanSheets: 15,
    saves: 78,
    penaltiesSaved: 1,
    yellowCards: 1,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 135,
    recentPoints: [6, 2, 11, 3, 6],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'martinez-23',
    name: 'Emiliano Martínez',
    club: 'Aston Villa',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 0,
    cleanSheets: 8,
    saves: 95,
    penaltiesSaved: 2,
    yellowCards: 5,
    redCards: 0,
    ownGoals: 1,
    penaltiesMissed: 0,
    points: 110,
    recentPoints: [3, 4, 1, 9, 2],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'alisson-01',
    name: 'Alisson Becker',
    club: 'Liverpool',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 1,
    cleanSheets: 11,
    saves: 65,
    penaltiesSaved: 0,
    yellowCards: 0,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 108,
    recentPoints: [6, 3, 2, 7, 6],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'ederson-31',
    name: 'Ederson Moraes',
    club: 'Man City',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 0,
    cleanSheets: 8,
    saves: 54,
    penaltiesSaved: 1,
    yellowCards: 2,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 98,
    recentPoints: [2, 1, 6, 2, 7],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'pickford-01',
    name: 'Jordan Pickford',
    club: 'Everton',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 0,
    cleanSheets: 10,
    saves: 112,
    penaltiesSaved: 1,
    yellowCards: 1,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 122,
    recentPoints: [3, 7, 2, 6, 12],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'pope-22',
    name: 'Nick Pope',
    club: 'Newcastle',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 0,
    cleanSheets: 8,
    saves: 85,
    penaltiesSaved: 0,
    yellowCards: 1,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 101,
    recentPoints: [2, 6, 3, 1, 4],
    ownershipStatus: { isOwned: false }
  },
  {
    id: 'onana-24',
    name: 'André Onana',
    club: 'Man Utd',
    position: 'GKP',
    injuryStatus: 'Available',
    goals: 0,
    assists: 0,
    cleanSheets: 8,
    saves: 105,
    penaltiesSaved: 1,
    yellowCards: 3,
    redCards: 0,
    ownGoals: 0,
    penaltiesMissed: 0,
    points: 114,
    recentPoints: [5, 4, 2, 8, 3],
    ownershipStatus: { isOwned: false }
  }
];
